### ISSUE TITLE
您好~请问一下后端这一块有什么教程么~

### ISSUE THREAD

**Issue by 2016WUJI01** [dailing57/XTTDR#2]
我是一名大三学生~之前使用vue+nodejs写过一版管理系统来完成课程任务，现在想要尝试使用springboot+vue来完成，目前对于后端如何完成接口api给前端vue使用产生了一些疑问，希望能够得到一些指导~

**Comment by dailing57** [comment]
springboot的教程可以上B站看看，很简单的。
前端设置跨域可以参考：[这个](https://github.com/dailing57/XTTDR/blob/main/frontend/tdr/vue.config.js)
后端设置跨域可以参考：[这个](https://github.com/dailing57/XTTDR/blob/main/backend/tdr/src/main/java/com/xttdr/common/config/CorsConfig.java)
